### ISSUE TITLE
crash in libucs in UCX 1.5.2 or 1.6 with OpenMPI 4.0.1 and mpi4py rdma tests 

### ISSUE THREAD

**Issue by azrael417** [openucx/ucx#4130]
I have built openmpi 4.0.1 against UCX 1.5.2 (and also 1.6) and get segmentation faults in libucs in mpi4py when it is compiled against this MPI. Here are my configure flags for UCX and OpenMPI:

```./autogen.sh
./configure CC=gcc CXX=g++ \
        --prefix=${UCX_PREFIX} --with-cuda=${CUDA_HOME} --enable-mt --disable-cma --with-ugni=no --with-xpmem=no```

with gcc 7.3.0 and cuda 10.1.168.
For OpenMPI:

```./configure CC=gcc CXX=g++ FC=gfortran F77=gfortran F90=gfortran CXXFLAGS="-march=native" CFLAGS="-march=native" FCFLAGS="-march=native" \
        --prefix=${OMPI_PREFIX} --with-cuda=${CUDA_HOME} \
        --with-ucx=${UCX_PREFIX} --with-slurm=${slurmdir} --with-pmi=${slurmdir} \
        --with-cray-pmi=no --with-alps=no --with-ugni=no --with-xpmem=no --with-cray-xpmem=no```

When I then compile mpi4py against this build, and run the rdma test:

``` srun -n 2 -c 5 python ./test_rma.py ```

I get:

```(mpi_test) tkurth@cgpu02:~/src/mpi4py/test> srun -n 2 -c 5 python ./test_rma.py
...[cgpu02:49063:0:49063] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1df8)
==== backtrace ====
    0  /usr/common/software/openmpi/4.0.1-ucx-1.5.2/gnu-7.3.0-cuda-10.1.168/ucx/lib/libucs.so.0(+0x21150) [0x2aaab96ad150]
    1  /usr/common/software/openmpi/4.0.1-ucx-1.5.2/gnu-7.3.0-cuda-10.1.168/ucx/lib/libucs.so.0(+0x213a4) [0x2aaab96ad3a4]
    2  /usr/common/software/openmpi/4.0.1-ucx-1.5.2/gnu-7.3.0-cuda-10.1.168/lib/openmpi/mca_btl_vader.so(+0x48c9) [0x2aaab5eac8c9]
    3  /usr/common/software/openmpi/4.0.1-ucx-1.5.2/gnu-7.3.0-cuda-10.1.168/lib/libopen-pal.so.40(opal_progress+0x2c) [0x2aaaac46a84c]
    4  /usr/common/software/openmpi/4.0.1-ucx-1.5.2/gnu-7.3.0-cuda-10.1.168/lib/openmpi/mca_osc_rdma.so(ompi_osc_rdma_compare_and_swap+0x605) [0x2aaac2104755]
    5  /usr/common/software/openmpi/4.0.1-ucx-1.5.2/gnu-7.3.0-cuda-10.1.168/lib/libmpi.so.40(PMPI_Compare_and_swap+0xf6) [0x2aaaabeabfb6]
    6  /global/homes/t/tkurth/.conda/envs/mpi_test/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so(+0xec6f5) [0x2aaaabd9e6f5]
    7  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyCFunction_FastCallDict+0x154) [0x555555665c54]
    8  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x199abc) [0x5555556edabc]
    9  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x30a) [0x55555571075a]
   10  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x193c5b) [0x5555556e7c5b]
   11  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x199b95) [0x5555556edb95]
   12  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x30a) [0x55555571075a]
   13  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x192e66) [0x5555556e6e66]
   14  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyFunction_FastCallDict+0x3d8) [0x5555556e8598]
   15  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x26f) [0x55555566601f]
   16  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_Call_Prepend+0x63) [0x55555566aaa3]
   17  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(PyObject_Call+0x3e) [0x555555665a5e]
   18  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x19e7) [0x555555711e37]
   19  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x192e66) [0x5555556e6e66]
   20  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyFunction_FastCallDict+0x1be) [0x5555556e837e]
   21  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x26f) [0x55555566601f]
   22  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_Call_Prepend+0x63) [0x55555566aaa3]
   23  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(PyObject_Call+0x3e) [0x555555665a5e]
   24  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x16b371) [0x5555556bf371]
   25  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x8b) [0x555555665e3b]
   26  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x199c0e) [0x5555556edc0e]
   27  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x30a) [0x55555571075a]
   28  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x192e66) [0x5555556e6e66]
   29  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyFunction_FastCallDict+0x3d8) [0x5555556e8598]
   30  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x26f) [0x55555566601f]
   31  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_Call_Prepend+0x63) [0x55555566aaa3]
   32  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(PyObject_Call+0x3e) [0x555555665a5e]
   33  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x19e7) [0x555555711e37]
   34  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x192e66) [0x5555556e6e66]
   35  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyFunction_FastCallDict+0x1be) [0x5555556e837e]
   36  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x26f) [0x55555566601f]
   37  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_Call_Prepend+0x63) [0x55555566aaa3]
   38  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(PyObject_Call+0x3e) [0x555555665a5e]
   39  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x16b371) [0x5555556bf371]
   40  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x8b) [0x555555665e3b]
   41  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x199c0e) [0x5555556edc0e]
   42  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x30a) [0x55555571075a]
   43  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x192e66) [0x5555556e6e66]
   44  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyFunction_FastCallDict+0x3d8) [0x5555556e8598]
   45  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x26f) [0x55555566601f]
   46  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_Call_Prepend+0x63) [0x55555566aaa3]
   47  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(PyObject_Call+0x3e) [0x555555665a5e]
   48  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x19e7) [0x555555711e37]
   49  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x192e66) [0x5555556e6e66]
   50  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyFunction_FastCallDict+0x1be) [0x5555556e837e]
   51  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x26f) [0x55555566601f]
   52  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_Call_Prepend+0x63) [0x55555566aaa3]
   53  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(PyObject_Call+0x3e) [0x555555665a5e]
   54  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x16b371) [0x5555556bf371]
   55  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyObject_FastCallDict+0x8b) [0x555555665e3b]
   56  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x199c0e) [0x5555556edc0e]
   57  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x30a) [0x55555571075a]
   58  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x193c5b) [0x5555556e7c5b]
   59  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(+0x199b95) [0x5555556edb95]
   60  /global/homes/t/tkurth/.conda/envs/mpi_test/bin/python(_PyEval_EvalFrameDefault+0x30a) [0x55555571075a]
===================
srun: error: cgpu02: task 1: Segmentation fault
srun: Terminating job step 229841.3
..............E...slurmstepd: error: *** STEP 229841.3 ON cgpu02 CANCELLED AT 2019-09-01T16:37:57 ***
srun: error: cgpu02: task 0: Terminated
srun: Force Terminated job step 229841.3
```

When I build the OSU MPI single sided benchmarks with this MPI directly I can run them without any issues. That makes me think this has to do with the python bindings to MPI are achieved, potentially some buffers do not survive the python/c boundary and get deallocated.
Let me know if I can assist with debugging this, it is crucial for us to get this to work.

**Comment by yosefe** [comment]
@azrael417 can you please check with UCX master? there were a few fixes related to cuda, malloc hooks, and python bindings.

**Comment by yosefe** [comment]
@azrael417 actually, i see the problem is coming from mca_btl_vader.so, which means OpenMPI uses osc/rdma instead of osc/ucx. Can you please run with "env OMPI_MCA_osc=ucx" ?

**Comment by azrael417** [comment]
Hello Yosefe,

that helped a bit, now the error is:

```(mpi_test) tkurth@cgpu04:~/src/mpi4py/test> srun -n 2 -c 5 python ./test_rma.py
[1567438731.422097] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422208] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422238] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422256] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422299] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 2
[1567438731.422317] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 2)
[1567438731.422333] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 2
[1567438731.422392] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 4)
[1567438731.422409] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095712, size 4)
[1567438731.422457] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 8)
[1567438731.422474] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095712, size 8)
[1567438731.422522] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 8)
[1567438731.422554] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095712, size 8)
[1567438731.422622] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422663] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422684] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 1
[1567438731.422727] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 2
[1567438731.422750] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 2)
[1567438731.422769] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR invalid atomic operation size: 2
[1567438731.422830] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 4)
[1567438731.422850] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095712, size 4)
[1567438731.422906] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 8)
[1567438731.422923] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095712, size 8)
[1567438731.422975] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095711, size 8)
[1567438731.422993] [cgpu04:32451:0]       amo_send.c:122  UCX  ERROR atomic variable must be naturally aligned (remote address 0x555557095712, size 8)```

and much more of these. So there is some alignment issue. Do you know how to fix that?

Best and thanks so far.

**Comment by yosefe** [comment]
It's a problem in osc/ucx which passes 1/2 byte atomics to UCX,
@janjust was it fixed in OpenMPI master?

**Comment by janjust** [comment]
@yosefe no this issue is not resolved, I thought there was talk of supporting non 32/64 bit atomics in ucx sw atomics, if not, then we need to address this as part of the openmpi implementation
tagging @artpol84

**Comment by yosefe** [comment]
@janjust yes, OpenMPI OSC/UCX implementation should fallback to active messages if it's non 32/64. I think this is considered a bug because currently UCX API explicitly states that atomics are only 32 or 64bit (by ucp_init feature flags).
in addition, we can update UCP API (and sw atomics) to support non 32/64, but that's a new feature..

**Comment by shamisp** [comment]
Original 32/64 was driver by SHMEM spec. Probably for MPI we can try to expose more.
