### ISSUE TITLE
1.8.1-rc1 artifacts are for ucx 1.9

### ISSUE THREAD

**Issue by abellina** [openucx/ucx#5335]
The bits in the tagged v1.8.1-rc1 are incorrect (they point to this tag: https://github.com/openucx/ucx/releases/tag/v4.2.0)

Seems like what is producing these could have a hard coded sha of `afbb24a`

```
dpkg-deb -I ucx-v1.8.1-rc1-ubuntu18.04-mofed5.0-cuda10.1.deb
 new Debian package, version 2.0.
 size 1141660 bytes: control archive=3596 bytes.
     455 bytes,    11 lines      control
    6926 bytes,   107 lines      md5sums
      82 bytes,     7 lines   *  prerm                #!/bin/sh
     182 bytes,    11 lines      shlibs
      74 bytes,     2 lines      triggers
 Package: ucx
 Version: 1.9.afbb24a
 Architecture: amd64
 Maintainer: ucx-group@elist.ornl.gov
 Installed-Size: 5882
 Depends: cuda-compat-10-1, cuda-cudart-10-1, ibverbs-providers (>= 25), libc6 (>= 2.15), libgomp1 (>= 4.9), libibverbs1 (>= 28), libnuma1 (>= 2.0.11), librdmacm1 (>= 23)
 Section: libs
 Priority: extra
 Homepage: http://www.openucx.org
 Description: Unified Communication X
  UCX is a communication library implementing high-performance messaging.
```

And after installing:

```
ucx_info -v
# UCT version=1.9.0 revision afbb24a
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/usr --enable-examples
```

**Comment by abellina** [comment]
@shamisp FYI, noticed this while trying to test 1.8.1-rc1.

**Comment by shamisp** [comment]
@abellina thanks ! @yosefe - seem like current AZP scripts are broken, unless those have been uploaded manually.

**Comment by abellina** [comment]
Thanks @shamisp, @yosefe. I see this is merged now: https://github.com/openucx/ucx/pull/5331, will the `1.8.1-rc1` tag be overwritten? or is that rc2?

**Comment by amaslenn** [comment]
There is an issue with Azure pipeline configuration: it didn't remove files from the previous build, so it took the wrong `.deb`. I will update release pipeline to address this issue. Once this fix merged to v1.8.x I'll re-trigger build for rc1.

cc @yshestakov

**Comment by amaslenn** [comment]
I've made a fix (not PR'ed yet) and created two test releases:
1. [v42](https://github.com/openucx/ucx/releases/tag/v42) for `master` branch
2. [v43](https://github.com/openucx/ucx/releases/tag/v43) for `v1.8.x` branch. @abellina you can use this to check `v1.8.1-rc1` I've just added my fix for Azure pipeline on top of the `v1.8.1-rc1` tag.

From v43 release:
```sh
# dpkg-deb -I ucx-v43-ubuntu18.04-mofed5.0-cuda10.2.deb
 new Debian package, version 2.0.
 size 1057164 bytes: control archive=3496 bytes.
     455 bytes,    11 lines      control
    6700 bytes,   103 lines      md5sums
      82 bytes,     7 lines   *  prerm                #!/bin/sh
     182 bytes,    11 lines      shlibs
      74 bytes,     2 lines      triggers
 Package: ucx
 Version: 1.8.23bb8e6
 Architecture: amd64
 Maintainer: ucx-group@elist.ornl.gov
 Installed-Size: 5496
 Depends: cuda-compat-10-2, cuda-cudart-10-2, ibverbs-providers (>= 22), libc6 (>= 2.15), libgomp1 (>= 4.9), libibverbs1 (>= 28), libnuma1 (>= 2.0.11), librdmacm1 (>= 23)
 Section: libs
 Priority: extra
 Homepage: http://www.openucx.org
 Description: Unified Communication X
  UCX is a communication library implementing high-performance messaging.
```

From v42 release:
```sh
# dpkg-deb -I ucx-v42-ubuntu18.04-mofed5.0-cuda10.2.deb
 new Debian package, version 2.0.
 size 1158228 bytes: control archive=3684 bytes.
     455 bytes,    11 lines      control
    7203 bytes,   111 lines      md5sums
      82 bytes,     7 lines   *  prerm                #!/bin/sh
     182 bytes,    11 lines      shlibs
      74 bytes,     2 lines      triggers
 Package: ucx
 Version: 1.9.45880e6
 Architecture: amd64
 Maintainer: ucx-group@elist.ornl.gov
 Installed-Size: 5979
 Depends: cuda-compat-10-2, cuda-cudart-10-2, ibverbs-providers (>= 25), libc6 (>= 2.15), libgomp1 (>= 4.9), libibverbs1 (>= 28), libnuma1 (>= 2.0.11), librdmacm1 (>= 23)
 Section: libs
 Priority: extra
 Homepage: http://www.openucx.org
 Description: Unified Communication X
  UCX is a communication library implementing high-performance messaging.
```

**Comment by abellina** [comment]
Thanks @amaslenn. I was able to get the 1.8 version with tag 43 (as suggested):
```
# UCT version=1.8.1 revision 23bb8e6
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/usr
```

I noticed that the `v1.8.1-rc1` tag was updated, but the binaries are still the same, just FYI.

**Comment by amaslenn** [comment]
> I noticed that the `v1.8.1-rc1` tag was updated, but the binaries are still the same, just FYI.

Yep, I was wrong thinking I can fix it through pipeline re-run, it can be done only manually (will do that later).

**Comment by amaslenn** [comment]
@abellina @shamisp I've updated v1.8.1-rc1 .deb artifacts.
