### ISSUE TITLE
32bit AMO failure with RC

### ISSUE THREAD

**Issue by shamisp** [openucx/ucx#840]
Command line:
```
mpirun -np 2 -npernode 1 -H softiron-2,softiron-3 -x MLX5_CQE_SIZE=64 -x UCX_TLS=rc,ud ~/install/bin/ucx_perftest  -v -f -t ucp_add -s 4 
iterations,typical_lat,avg_lat,overall_lat,avg_bw,overall_bw,avg_mr,overall_mr
[1466440123.977312] [softiron-3:14172:0]         select.c:243  UCX  ERROR No atomic operations on registered memory transport to <no debug data>: rc/mlx5_0:1 - no 32-bit atomic add, ud/mlx5_0:1 - no 32-bit atomic add
[1466440123.977355] [softiron-3:14172:0]        libperf.c:795  UCX  ERROR ucp_ep_create() failed: Destination is unreachable
[1466440123.977403] [softiron-3:14172:0]        libperf.c:1025 UCX  ERROR Failed to setup endpoints: Destination is unreachable
[1466440123.975232] [softiron-2:15758:0]         select.c:243  UCX  ERROR No atomic operations on registered memory transport to softiron-3:14172: rc/mlx5_0:1 - no 32-bit atomic add, ud/mlx5_0:1 - no 32-bit atomic add
[1466440123.975277] [softiron-2:15758:0]        libperf.c:795  UCX  ERROR ucp_ep_create() failed: Destination is unreachable
[1466440123.975296] [softiron-2:15758:0]        libperf.c:1025 UCX  ERROR Failed to setup endpoints: Destination is unreachable
[1466440124.036006] [softiron-2:15758:0]       perftest.c:1118 UCX  ERROR Failed to run test: Destination is unreachable
[1466440124.045093] [softiron-3:14172:0]       perftest.c:1118 UCX  ERROR Failed to run test: Destination is unreachable
```

MLNX_OFED_LINUX-3.3-1.5.0.0 (OFED-3.3-1.5.0)
CX4 / 12.16.1006

**Comment by shamisp** [comment]
And the same works with mlx5:
```
mpirun -np 2 -npernode 1 -H softiron-2,softiron-3 -x MLX5_CQE_SIZE=64 -x UCX_TLS=rc_mlx5,ud ~/install/bin/ucx_perftest  -v -f -t ucp_add -s 4 
iterations,typical_lat,avg_lat,overall_lat,avg_bw,overall_bw,avg_mr,overall_mr
1000000,0.320,0.621,0.621,6.14,6.14,1609558,1609558

```

**Comment by shamisp** [comment]
FYI
```
device_cap_exp_flags:           0xFFFFFBFF00000000
                                        EXP_DC_TRANSPORT
                                        EXP_DEVICE_QPG
                                        EXP_UD_RSS
                                        EXP_UD_TSS
                                        EXP_MEM_WINDOW
                                        EXP_MEM_MGT_EXTENSIONS
                                        EXP_MW_TYPE_2A
                                        EXP_MW_TYPE_2B
                                        EXP_CROSS_CHANNEL
                                        EXP_MANAGED_FLOW_STEERING
                                        EXP_MR_ALLOCATE
                                        EXP_SHARED_MR
                                        EXT_ATOMICS
                                        EXT_SEND NOP
                                        EXP_UMR
                                        EXP_ODP
                                        EXP_RX_CSUM_TCP_UDP_PKT
                                        EXP_RX_CSUM_IP_PKT
                                        EXP_DC_INFO
                                        EXP_MASKED_ATOMICS
                                        EXP_RX_TCP_UDP_PKT_TYPE
                                        EXP_SCATTER_FCS
                                        Unknown flags: 0x8E1C230000000000
```

**Comment by yosefe** [comment]
@shamisp can you please attach output of `ucx_info -d`?

**Comment by shamisp** [comment]
```
#   component:        ib
#   allocate:         unlimited
#   register:         unlimited, cost: 90 nsec
#   remote key:       12 bytes
#
#   Transport: rc
#
#   Device: mlx5_0:1 
#
#      capabilities: 
#           bandwidth:     11794.23 MB/sec
#           latency:       600 nsec
#           overhead:      75 nsec
#            put_short: <= 92
#            put_bcopy: <= 8192
#            put_zcopy: <= 1024 MiB
#            get_bcopy: <= 8192
#            get_zcopy: <= 1024 MiB
#             am_short: <= 91
#             am_bcopy: <= 8191
#             am_zcopy: <= 8191
#            am header: <= 127
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#          atomic_swap: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#       device address: 3 bytes
#           ep address: 3 bytes
#       error handling: none

```

**Comment by shamisp** [comment]
from the config.h
```
./config.h:82:/* Define to 1 if you have the declaration of `IBV_EXP_ATOMIC_HCA_REPLY_BE',
./config.h:84:#define HAVE_DECL_IBV_EXP_ATOMIC_HCA_REPLY_BE 1
./config.h:111:   `IBV_EXP_QP_INIT_ATTR_ATOMICS_ARG', and to 0 if you don't. */
./config.h:112:#define HAVE_DECL_IBV_EXP_QP_INIT_ATTR_ATOMICS_ARG 1
./config.h:115:   `IBV_EXP_SEND_EXT_ATOMIC_INLINE', and to 0 if you don't. */
./config.h:116:#define HAVE_DECL_IBV_EXP_SEND_EXT_ATOMIC_INLINE 1
./config.h:123:   `IBV_EXP_WR_EXT_MASKED_ATOMIC_CMP_AND_SWP', and to 0 if you don't. */
./config.h:124:#define HAVE_DECL_IBV_EXP_WR_EXT_MASKED_ATOMIC_CMP_AND_SWP 1
./config.h:127:   `IBV_EXP_WR_EXT_MASKED_ATOMIC_FETCH_AND_ADD', and to 0 if you don't. */
./config.h:128:#define HAVE_DECL_IBV_EXP_WR_EXT_MASKED_ATOMIC_FETCH_AND_ADD 1
./config.h:180:#define HAVE_IB_EXT_ATOMICS 1
```

**Comment by shamisp** [comment]
Seems like the issue was solved in master.

**Comment by abouteiller** [comment]
I still experience this issue on my side. 

Connexion with UCT works, problem is only when using `ucp_ep`

From OpenSHMEM (UH ref over UCX)
```
[1472068253.953380] [arc00:17982:0]         select.c:107  UCX  TRACE cm/mlx4_0:2 : not suitable for remote allocated memory access, no put short
[1472068253.953384] [arc00:17982:0]         select.c:107  UCX  TRACE ud/mlx4_0:2 : not suitable for remote allocated memory access, no put short
[1472068253.953390] [arc00:17982:0]         select.c:175  UCX  TRACE addr[0]: no 32-bit atomic add
[1472068253.953394] [arc00:17982:0]         select.c:175  UCX  TRACE addr[1]: no 32-bit atomic add
[1472068253.953398] [arc00:17982:0]         select.c:175  UCX  TRACE addr[2]: no 32-bit atomic add
[1472068253.953402] [arc00:17982:0]         select.c:168  UCX  TRACE addr[3]: no memory registration
[1472068253.953405] [arc00:17982:0]         select.c:168  UCX  TRACE addr[4]: no memory registration
[1472068253.953410] [arc00:17982:0]         select.c:107  UCX  TRACE cuda/gpu0 : not suitable for atomic operations on registered memory, no pending
[1472068253.953414] [arc00:17982:0]         select.c:107  UCX  TRACE cm/mlx4_0:2 : not suitable for atomic operations on registered memory, no 32-bit atomic add
[1472068253.953418] [arc00:17982:0]         select.c:107  UCX  TRACE ud/mlx4_0:2 : not suitable for atomic operations on registered memory, no 32-bit atomic add
[1472068253.953423] [arc00:17982:0]         select.c:107  UCX  TRACE rc/mlx4_0:2 : not suitable for atomic operations on registered memory, no 32-bit atomic add
[1472068253.953428] [arc00:17982:0]         select.c:256  UCX  ERROR No atomic operations on registered memory transport to arc00:17982: cuda/gpu0 - no pending, cm/mlx4_0:2 - no 32-bit atomic add, ud/mlx4_0:2 - no 32-bit atomic add, rc/mlx4_0:2 - no 32-bit atomic add, mm/posix - cannot reach remote worker, mm/sysv - cannot reach remote worker
[1472068253.953441] [arc00:17982:0]         ucp_ep.c:219  UCX  DEBUG destroy ep 0xef16a0
```

The cards:  (FDR with an old OFED 1.5 driver)
```
#   Transport: rc
#
#   Device: mlx4_0:2
#
#      capabilities:
#           bandwidth:     6433.22 MB/sec
#           latency:       700 nsec
#           overhead:      75 nsec
#            put_short: <= 88
#            put_bcopy: <= 8192
#            put_zcopy: <= 1024 MiB
#            get_bcopy: <= 8192
#            get_zcopy: <= 1024 MiB
#             am_short: <= 87
#             am_bcopy: <= 8191
#             am_zcopy: <= 8191
#            am header: <= 127
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#       device address: 3 bytes
#           ep address: 3 bytes
#       error handling: peer failure
#
```

The config.h
```
10 /* Define to 1 if you have the declaration of                                                                                                                                                                  
111    `IBV_EXP_QP_INIT_ATTR_ATOMICS_ARG', and to 0 if you don't. */
112 #define HAVE_DECL_IBV_EXP_QP_INIT_ATTR_ATOMICS_ARG 0
113 
114 /* Define to 1 if you have the declaration of
115    `IBV_EXP_SEND_EXT_ATOMIC_INLINE', and to 0 if you don't. */
116 #define HAVE_DECL_IBV_EXP_SEND_EXT_ATOMIC_INLINE 0
117 
118 /* Define to 1 if you have the declaration of `ibv_exp_setenv', and to 0 if
119    you don't. */
120 #define HAVE_DECL_IBV_EXP_SETENV 0
121 
122 /* Define to 1 if you have the declaration of
123    `IBV_EXP_WR_EXT_MASKED_ATOMIC_CMP_AND_SWP', and to 0 if you don't. */
124 #define HAVE_DECL_IBV_EXP_WR_EXT_MASKED_ATOMIC_CMP_AND_SWP 0
125 
126 /* Define to 1 if you have the declaration of
127    `IBV_EXP_WR_EXT_MASKED_ATOMIC_FETCH_AND_ADD', and to 0 if you don't. */
128 #define HAVE_DECL_IBV_EXP_WR_EXT_MASKED_ATOMIC_FETCH_AND_ADD 0
129 
130 /* Define to 1 if you have the declaration of `IBV_EXP_WR_NOP', and to 0 if
131    you don't. */
132 #define HAVE_DECL_IBV_EXP_WR_NOP 0
133 
134 /* Define to 1 if you have the declaration of `IBV_LINK_LAYER_INFINIBAND', and
135    to 0 if you don't. */
136 #define HAVE_DECL_IBV_LINK_LAYER_INFINIBAND 1
```
